// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.33.0

package proto.common;

@com.google.protobuf.Generated
public interface SharedVariableUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SharedVariableUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 newValue = 1;</code>
   * @return The newValue.
   */
  int getNewValue();
}
