// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connection.proto
// Protobuf Java Version: 4.33.0

package proto.connection;

@com.google.protobuf.Generated
public interface AllNetworkNodesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllNetworkNodes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  java.util.List<proto.connection.Join> 
      getNodesAddressesList();
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  proto.connection.Join getNodesAddresses(int index);
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  int getNodesAddressesCount();
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  java.util.List<? extends proto.connection.JoinOrBuilder> 
      getNodesAddressesOrBuilderList();
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  proto.connection.JoinOrBuilder getNodesAddressesOrBuilder(
      int index);

  /**
   * <code>string receiverServerId = 2;</code>
   * @return The receiverServerId.
   */
  java.lang.String getReceiverServerId();
  /**
   * <code>string receiverServerId = 2;</code>
   * @return The bytes for receiverServerId.
   */
  com.google.protobuf.ByteString
      getReceiverServerIdBytes();
}
