// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connection.proto
// Protobuf Java Version: 4.33.0

package proto.connection;

/**
 * <pre>
 * todo add server id to all addresses
 * </pre>
 *
 * Protobuf type {@code AllNetworkNodes}
 */
@com.google.protobuf.Generated
public final class AllNetworkNodes extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AllNetworkNodes)
    AllNetworkNodesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "AllNetworkNodes");
  }
  // Use AllNetworkNodes.newBuilder() to construct.
  private AllNetworkNodes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AllNetworkNodes() {
    nodesAddresses_ = java.util.Collections.emptyList();
    receiverServerId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.connection.ConnectionProto.internal_static_AllNetworkNodes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.connection.ConnectionProto.internal_static_AllNetworkNodes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.connection.AllNetworkNodes.class, proto.connection.AllNetworkNodes.Builder.class);
  }

  public static final int NODESADDRESSES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<proto.connection.Join> nodesAddresses_;
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.connection.Join> getNodesAddressesList() {
    return nodesAddresses_;
  }
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.connection.JoinOrBuilder> 
      getNodesAddressesOrBuilderList() {
    return nodesAddresses_;
  }
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  @java.lang.Override
  public int getNodesAddressesCount() {
    return nodesAddresses_.size();
  }
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  @java.lang.Override
  public proto.connection.Join getNodesAddresses(int index) {
    return nodesAddresses_.get(index);
  }
  /**
   * <code>repeated .Join nodesAddresses = 1;</code>
   */
  @java.lang.Override
  public proto.connection.JoinOrBuilder getNodesAddressesOrBuilder(
      int index) {
    return nodesAddresses_.get(index);
  }

  public static final int RECEIVERSERVERID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object receiverServerId_ = "";
  /**
   * <code>string receiverServerId = 2;</code>
   * @return The receiverServerId.
   */
  @java.lang.Override
  public java.lang.String getReceiverServerId() {
    java.lang.Object ref = receiverServerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiverServerId_ = s;
      return s;
    }
  }
  /**
   * <code>string receiverServerId = 2;</code>
   * @return The bytes for receiverServerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverServerIdBytes() {
    java.lang.Object ref = receiverServerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiverServerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < nodesAddresses_.size(); i++) {
      output.writeMessage(1, nodesAddresses_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiverServerId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, receiverServerId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < nodesAddresses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, nodesAddresses_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiverServerId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, receiverServerId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.connection.AllNetworkNodes)) {
      return super.equals(obj);
    }
    proto.connection.AllNetworkNodes other = (proto.connection.AllNetworkNodes) obj;

    if (!getNodesAddressesList()
        .equals(other.getNodesAddressesList())) return false;
    if (!getReceiverServerId()
        .equals(other.getReceiverServerId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNodesAddressesCount() > 0) {
      hash = (37 * hash) + NODESADDRESSES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesAddressesList().hashCode();
    }
    hash = (37 * hash) + RECEIVERSERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverServerId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.connection.AllNetworkNodes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.connection.AllNetworkNodes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.connection.AllNetworkNodes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.connection.AllNetworkNodes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.connection.AllNetworkNodes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.connection.AllNetworkNodes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.connection.AllNetworkNodes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * todo add server id to all addresses
   * </pre>
   *
   * Protobuf type {@code AllNetworkNodes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AllNetworkNodes)
      proto.connection.AllNetworkNodesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.connection.ConnectionProto.internal_static_AllNetworkNodes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.connection.ConnectionProto.internal_static_AllNetworkNodes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.connection.AllNetworkNodes.class, proto.connection.AllNetworkNodes.Builder.class);
    }

    // Construct using proto.connection.AllNetworkNodes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (nodesAddressesBuilder_ == null) {
        nodesAddresses_ = java.util.Collections.emptyList();
      } else {
        nodesAddresses_ = null;
        nodesAddressesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      receiverServerId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.connection.ConnectionProto.internal_static_AllNetworkNodes_descriptor;
    }

    @java.lang.Override
    public proto.connection.AllNetworkNodes getDefaultInstanceForType() {
      return proto.connection.AllNetworkNodes.getDefaultInstance();
    }

    @java.lang.Override
    public proto.connection.AllNetworkNodes build() {
      proto.connection.AllNetworkNodes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.connection.AllNetworkNodes buildPartial() {
      proto.connection.AllNetworkNodes result = new proto.connection.AllNetworkNodes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(proto.connection.AllNetworkNodes result) {
      if (nodesAddressesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          nodesAddresses_ = java.util.Collections.unmodifiableList(nodesAddresses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nodesAddresses_ = nodesAddresses_;
      } else {
        result.nodesAddresses_ = nodesAddressesBuilder_.build();
      }
    }

    private void buildPartial0(proto.connection.AllNetworkNodes result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.receiverServerId_ = receiverServerId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.connection.AllNetworkNodes) {
        return mergeFrom((proto.connection.AllNetworkNodes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.connection.AllNetworkNodes other) {
      if (other == proto.connection.AllNetworkNodes.getDefaultInstance()) return this;
      if (nodesAddressesBuilder_ == null) {
        if (!other.nodesAddresses_.isEmpty()) {
          if (nodesAddresses_.isEmpty()) {
            nodesAddresses_ = other.nodesAddresses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodesAddressesIsMutable();
            nodesAddresses_.addAll(other.nodesAddresses_);
          }
          onChanged();
        }
      } else {
        if (!other.nodesAddresses_.isEmpty()) {
          if (nodesAddressesBuilder_.isEmpty()) {
            nodesAddressesBuilder_.dispose();
            nodesAddressesBuilder_ = null;
            nodesAddresses_ = other.nodesAddresses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nodesAddressesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetNodesAddressesFieldBuilder() : null;
          } else {
            nodesAddressesBuilder_.addAllMessages(other.nodesAddresses_);
          }
        }
      }
      if (!other.getReceiverServerId().isEmpty()) {
        receiverServerId_ = other.receiverServerId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              proto.connection.Join m =
                  input.readMessage(
                      proto.connection.Join.parser(),
                      extensionRegistry);
              if (nodesAddressesBuilder_ == null) {
                ensureNodesAddressesIsMutable();
                nodesAddresses_.add(m);
              } else {
                nodesAddressesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              receiverServerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<proto.connection.Join> nodesAddresses_ =
      java.util.Collections.emptyList();
    private void ensureNodesAddressesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nodesAddresses_ = new java.util.ArrayList<proto.connection.Join>(nodesAddresses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        proto.connection.Join, proto.connection.Join.Builder, proto.connection.JoinOrBuilder> nodesAddressesBuilder_;

    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public java.util.List<proto.connection.Join> getNodesAddressesList() {
      if (nodesAddressesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodesAddresses_);
      } else {
        return nodesAddressesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public int getNodesAddressesCount() {
      if (nodesAddressesBuilder_ == null) {
        return nodesAddresses_.size();
      } else {
        return nodesAddressesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public proto.connection.Join getNodesAddresses(int index) {
      if (nodesAddressesBuilder_ == null) {
        return nodesAddresses_.get(index);
      } else {
        return nodesAddressesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder setNodesAddresses(
        int index, proto.connection.Join value) {
      if (nodesAddressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesAddressesIsMutable();
        nodesAddresses_.set(index, value);
        onChanged();
      } else {
        nodesAddressesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder setNodesAddresses(
        int index, proto.connection.Join.Builder builderForValue) {
      if (nodesAddressesBuilder_ == null) {
        ensureNodesAddressesIsMutable();
        nodesAddresses_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodesAddressesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder addNodesAddresses(proto.connection.Join value) {
      if (nodesAddressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesAddressesIsMutable();
        nodesAddresses_.add(value);
        onChanged();
      } else {
        nodesAddressesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder addNodesAddresses(
        int index, proto.connection.Join value) {
      if (nodesAddressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesAddressesIsMutable();
        nodesAddresses_.add(index, value);
        onChanged();
      } else {
        nodesAddressesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder addNodesAddresses(
        proto.connection.Join.Builder builderForValue) {
      if (nodesAddressesBuilder_ == null) {
        ensureNodesAddressesIsMutable();
        nodesAddresses_.add(builderForValue.build());
        onChanged();
      } else {
        nodesAddressesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder addNodesAddresses(
        int index, proto.connection.Join.Builder builderForValue) {
      if (nodesAddressesBuilder_ == null) {
        ensureNodesAddressesIsMutable();
        nodesAddresses_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodesAddressesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder addAllNodesAddresses(
        java.lang.Iterable<? extends proto.connection.Join> values) {
      if (nodesAddressesBuilder_ == null) {
        ensureNodesAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodesAddresses_);
        onChanged();
      } else {
        nodesAddressesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder clearNodesAddresses() {
      if (nodesAddressesBuilder_ == null) {
        nodesAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nodesAddressesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public Builder removeNodesAddresses(int index) {
      if (nodesAddressesBuilder_ == null) {
        ensureNodesAddressesIsMutable();
        nodesAddresses_.remove(index);
        onChanged();
      } else {
        nodesAddressesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public proto.connection.Join.Builder getNodesAddressesBuilder(
        int index) {
      return internalGetNodesAddressesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public proto.connection.JoinOrBuilder getNodesAddressesOrBuilder(
        int index) {
      if (nodesAddressesBuilder_ == null) {
        return nodesAddresses_.get(index);  } else {
        return nodesAddressesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public java.util.List<? extends proto.connection.JoinOrBuilder> 
         getNodesAddressesOrBuilderList() {
      if (nodesAddressesBuilder_ != null) {
        return nodesAddressesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodesAddresses_);
      }
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public proto.connection.Join.Builder addNodesAddressesBuilder() {
      return internalGetNodesAddressesFieldBuilder().addBuilder(
          proto.connection.Join.getDefaultInstance());
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public proto.connection.Join.Builder addNodesAddressesBuilder(
        int index) {
      return internalGetNodesAddressesFieldBuilder().addBuilder(
          index, proto.connection.Join.getDefaultInstance());
    }
    /**
     * <code>repeated .Join nodesAddresses = 1;</code>
     */
    public java.util.List<proto.connection.Join.Builder> 
         getNodesAddressesBuilderList() {
      return internalGetNodesAddressesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        proto.connection.Join, proto.connection.Join.Builder, proto.connection.JoinOrBuilder> 
        internalGetNodesAddressesFieldBuilder() {
      if (nodesAddressesBuilder_ == null) {
        nodesAddressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            proto.connection.Join, proto.connection.Join.Builder, proto.connection.JoinOrBuilder>(
                nodesAddresses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        nodesAddresses_ = null;
      }
      return nodesAddressesBuilder_;
    }

    private java.lang.Object receiverServerId_ = "";
    /**
     * <code>string receiverServerId = 2;</code>
     * @return The receiverServerId.
     */
    public java.lang.String getReceiverServerId() {
      java.lang.Object ref = receiverServerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverServerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receiverServerId = 2;</code>
     * @return The bytes for receiverServerId.
     */
    public com.google.protobuf.ByteString
        getReceiverServerIdBytes() {
      java.lang.Object ref = receiverServerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverServerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receiverServerId = 2;</code>
     * @param value The receiverServerId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverServerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      receiverServerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string receiverServerId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverServerId() {
      receiverServerId_ = getDefaultInstance().getReceiverServerId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string receiverServerId = 2;</code>
     * @param value The bytes for receiverServerId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverServerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      receiverServerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AllNetworkNodes)
  }

  // @@protoc_insertion_point(class_scope:AllNetworkNodes)
  private static final proto.connection.AllNetworkNodes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.connection.AllNetworkNodes();
  }

  public static proto.connection.AllNetworkNodes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllNetworkNodes>
      PARSER = new com.google.protobuf.AbstractParser<AllNetworkNodes>() {
    @java.lang.Override
    public AllNetworkNodes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AllNetworkNodes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllNetworkNodes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.connection.AllNetworkNodes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

