// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connection.proto
// Protobuf Java Version: 4.33.0

package proto.connection;

@com.google.protobuf.Generated
public final class ConnectionProto extends com.google.protobuf.GeneratedFile {
  private ConnectionProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ConnectionProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Join_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Join_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JoinResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllNetworkNodes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AllNetworkNodes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeDied_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NodeDied_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020connection.proto\032\014common.proto\032\033google" +
      "/protobuf/empty.proto\"3\n\004Join\022\031\n\007address" +
      "\030\001 \001(\0132\010.Address\022\020\n\010serverId\030\002 \001(\t\" \n\014Jo" +
      "inResponse\022\020\n\010serverId\030\001 \001(\t\"J\n\017AllNetwo" +
      "rkNodes\022\035\n\016nodesAddresses\030\001 \003(\0132\005.Join\022\030" +
      "\n\020receiverServerId\030\002 \001(\t\"7\n\010NodeDied\022\031\n\007" +
      "address\030\001 \001(\0132\010.Address\022\020\n\010serverId\030\002 \001(" +
      "\t2\307\001\n\013JoinNetwork\0221\n\024JoinWithNodesReques" +
      "t\022\005.Join\032\020.AllNetworkNodes\"\000\022$\n\nJoinToNo" +
      "de\022\005.Join\032\r.JoinResponse\"\000\022*\n\004Ping\022\010.Add" +
      "ress\032\026.google.protobuf.Empty\"\000\0223\n\014NodeDi" +
      "edInfo\022\t.NodeDied\032\026.google.protobuf.Empt" +
      "y\"\000B%\n\020proto.connectionB\017ConnectionProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.common.CommonProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_Join_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Join_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Join_descriptor,
        new java.lang.String[] { "Address", "ServerId", });
    internal_static_JoinResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_JoinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_JoinResponse_descriptor,
        new java.lang.String[] { "ServerId", });
    internal_static_AllNetworkNodes_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_AllNetworkNodes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AllNetworkNodes_descriptor,
        new java.lang.String[] { "NodesAddresses", "ReceiverServerId", });
    internal_static_NodeDied_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_NodeDied_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NodeDied_descriptor,
        new java.lang.String[] { "Address", "ServerId", });
    descriptor.resolveAllFeaturesImmutable();
    proto.common.CommonProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
