// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connection.proto
// Protobuf Java Version: 4.33.0

package proto.connection;

@com.google.protobuf.Generated
public interface JoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverId = 1;</code>
   * @return The serverId.
   */
  java.lang.String getServerId();
  /**
   * <code>string serverId = 1;</code>
   * @return The bytes for serverId.
   */
  com.google.protobuf.ByteString
      getServerIdBytes();
}
