// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: connection.proto
// Protobuf Java Version: 4.33.0

package proto.connection;

@com.google.protobuf.Generated
public interface NodeDiedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeDied)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 1;</code>
   * @return The address.
   */
  proto.common.Address getAddress();
  /**
   * <code>.Address address = 1;</code>
   */
  proto.common.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>string serverId = 2;</code>
   * @return The serverId.
   */
  java.lang.String getServerId();
  /**
   * <code>string serverId = 2;</code>
   * @return The bytes for serverId.
   */
  com.google.protobuf.ByteString
      getServerIdBytes();
}
