// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sharedMutex.proto
// Protobuf Java Version: 4.33.0

package proto.sharedMutex;

@com.google.protobuf.Generated
public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 1;</code>
   * @return The address.
   */
  proto.common.Address getAddress();
  /**
   * <code>.Address address = 1;</code>
   */
  proto.common.AddressOrBuilder getAddressOrBuilder();
}
