// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sharedMutex.proto
// Protobuf Java Version: 4.33.0

package proto.sharedMutex;

@com.google.protobuf.Generated
public final class SharedMutexProto extends com.google.protobuf.GeneratedFile {
  private SharedMutexProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "SharedMutexProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Reply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SharedVariableUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SharedVariableUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021sharedMutex.proto\032\014common.proto\032\033googl" +
      "e/protobuf/empty.proto\"$\n\007Request\022\031\n\007add" +
      "ress\030\001 \001(\0132\010.Address\"\"\n\005Reply\022\031\n\007address" +
      "\030\001 \001(\0132\010.Address\"(\n\024SharedVariableUpdate" +
      "\022\020\n\010newValue\030\001 \001(\0052\300\001\n\013SharedMutex\0225\n\017re" +
      "gisterRequest\022\010.Request\032\026.google.protobu" +
      "f.Empty\"\000\0221\n\rregisterReply\022\006.Reply\032\026.goo" +
      "gle.protobuf.Empty\"\000\022G\n\024updateSharedVari" +
      "able\022\025.SharedVariableUpdate\032\026.google.pro" +
      "tobuf.Empty\"\000B\'\n\021proto.sharedMutexB\020Shar" +
      "edMutexProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.common.CommonProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Address", });
    internal_static_Reply_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Reply_descriptor,
        new java.lang.String[] { "Address", });
    internal_static_SharedVariableUpdate_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_SharedVariableUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SharedVariableUpdate_descriptor,
        new java.lang.String[] { "NewValue", });
    descriptor.resolveAllFeaturesImmutable();
    proto.common.CommonProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
